// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW5P5pwJ4piCh27pSeFjrAi0kom9VUUDo',
    appId: '1:1090046355909:web:2ca08423eb1ff12f3b03ac',
    messagingSenderId: '1090046355909',
    projectId: 'sgew-2c59f',
    authDomain: 'sgew-2c59f.firebaseapp.com',
    storageBucket: 'sgew-2c59f.firebasestorage.app',
    measurementId: 'G-MX4F0GDK6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOTXaURVhOY8bRf6AF6WaXQsHFsdYNQ7g',
    appId: '1:1090046355909:android:0fe75409466780d13b03ac',
    messagingSenderId: '1090046355909',
    projectId: 'sgew-2c59f',
    storageBucket: 'sgew-2c59f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq_9l99txH_wAL4AydQ8Gx8-ko2U-JYQI',
    appId: '1:1090046355909:ios:688945fdab50c39d3b03ac',
    messagingSenderId: '1090046355909',
    projectId: 'sgew-2c59f',
    storageBucket: 'sgew-2c59f.firebasestorage.app',
    iosBundleId: 'com.sgew.sgew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq_9l99txH_wAL4AydQ8Gx8-ko2U-JYQI',
    appId: '1:1090046355909:ios:688945fdab50c39d3b03ac',
    messagingSenderId: '1090046355909',
    projectId: 'sgew-2c59f',
    storageBucket: 'sgew-2c59f.firebasestorage.app',
    iosBundleId: 'com.sgew.sgew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW5P5pwJ4piCh27pSeFjrAi0kom9VUUDo',
    appId: '1:1090046355909:web:1d802dfb966871363b03ac',
    messagingSenderId: '1090046355909',
    projectId: 'sgew-2c59f',
    authDomain: 'sgew-2c59f.firebaseapp.com',
    storageBucket: 'sgew-2c59f.firebasestorage.app',
    measurementId: 'G-8QRZ7HP2EQ',
  );
}
